### ISSUE TITLE
How to handle fork with TypeScript

### ISSUE THREAD

**Issue by toddobryan** [playframework/play-scala-react-seed#28]
I've created a fork of this repo using TypeScript instead of vanilla JS and changing some things to make them more modern, like using hooks, async/await instead of callbacks, etc.

https://github.com/toddobryan/scala-play-react-typescript-seed

I'm happy to share this back, but I don't know if that's the right thing to do or how to do it. Some people might not want TypeScript, so I don't know if you want to create different branches on this repo or if I should just keep my fork separate and maybe you could include a link for people who are interested in TypeScript.

Just let me know the easiest way to deal with this, and I'm happy to oblige.

**Comment by ptrdom** [comment]
You could submit a request to share your project under playframework GitHub organization's seed projects.
