### ISSUE TITLE
 react-scripts: not found

### ISSUE THREAD

**Issue by Lucasnobrepro** [playframework/play-scala-react-seed#31]
I use SBT run returns

sh: 1: react-scripts: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! scala-play-react-seed@1.0.0 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the scala-play-react-seed@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ptrdom** [comment]
This is covered under CI tests and should not happen, must be an issue with your local environment.
