### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by ptrdom** [playframework/play-scala-react-seed#50]
I wanted to add some improvements to the setup, but the last commit to master was a while ago, and there already are beneficial PRs that seem to be stale, so I wonder if I should just fork it instead of producing a PR here and continue the work on this template in a new repository.

Thoughts?

**Comment by theilig** [comment]
@ptrdom 
did you end up doing that?  I hate to fork off since this was a really helpful repo, but as the dependencies get more and more out of date it's going to lose usefulness.  I'd prefer not to host it myself since I'm not really a front-end person, and npm dazzles and confuses me, however I'd be happy to try to carry the torch with others

**Comment by ptrdom** [comment]
@theilig I did not end up doing it, was not absolutely sure how to approach it. I was thinking about straight up copying the repository over, keeping the commit history and altering README to explain why the copying was done. Though ideally I think we would ask GitHub Support to change the ownership, since it seems like the owner simply disappeared, but I have a feeling GitHub Support would not be able to help us out here.

**Comment by ptrdom** [comment]
Asking a larger organization, for example https://github.com/playframework, if we could move this under them would make a lot of sense too I think, so the same problem that we are discussing now could be potentially avoided in the future.

**Comment by ptrdom** [comment]
@theilig Let's see what Play's maintainers say - https://discord.com/channels/931647755942776882/931955762748616714/954713192796397610.

**Comment by mkurz** [comment]
@yohangz I just wrote you an email and a message on LinkedIn about moving this repository to the Play Framework organization. An answer would be highly appreciated :wink: Thank you very much!

**Comment by yohangz** [comment]
Sorry about the delayed response. I went ahead with the transfer. Thank you all for your interest in actively maintaining this project. That means a lot to me. I'm really sorry about the delayed response.

**Comment by mkurz** [comment]
@yohangz Actually, I just saw that you transfered the [scala-play-angular-seed](https://github.com/playframework/scala-play-angular-seed) repository, but not this one here, the scala-play-react-seed :rofl:

**Comment by mkurz** [comment]
@lahiruz @sanuradhag @Arty26 You did maintain all those `[scala|java]-play-[angular|react]-seed` projects before. Are you still interested in the projects? Should I add you to the GitHub maintainers team after we transfered the repositories over to the Play Framework organization?

**Comment by sanuradhag** [comment]
@mkurz yes that would be great 👍

**Comment by mkurz** [comment]
@sanuradhag Send you an invite. You will then have maintain rights https://github.com/playframework/scala-play-angular-seed and the other repos once we transfered them.

**Comment by mkurz** [comment]
Alright, so all the repos have been transfered, @ptrdom you should have maintainer access right now. 
I renamed the repos to fit our existing naming scheme (`scala-play-...` -> `play-scala-...`, `java-play-...` -> `play-java-...`). Nice thing being GitHub will redirect from old name to the new url anyway.

Also be aware that I renamed the `master` branch to `main` for each repo, so you might need to adjust that locally (you should see a tooltip from GitHub that helps you with that when you go to the repos web page)

So these are the repos you can maintain now:
* https://github.com/playframework/play-java-react-seed
* https://github.com/playframework/play-scala-react-seed
* https://github.com/playframework/play-java-angular-seed
* https://github.com/playframework/play-scala-angular-seed

If you need anything else please let me know!
Thanks!

**Comment by ihostage** [comment]
How about very similar repos for Vue JS? 🤔 
https://github.com/duncannevin/scala-play-vue-seed
https://github.com/duncannevin/java-play-vue-seed

**Comment by mkurz** [comment]
@ihostage I was thinking about that as well, however someone has to maintain them. IMHO it does not make sense to move them all to the play org if no one will take care of them and they will just rot there...
I mean, yes we can move them, maybe the chance is higher to find someone.

**Comment by ihostage** [comment]
@mkurz Yep, you are right. Also maybe it's possible find a way to merge them all for decreasing a cost of maintaining all. Need to think about that 🤔
