### ISSUE TITLE
Basic CI with GitHub actions

### ISSUE THREAD

**Issue by ptrdom** [playframework/play-scala-react-seed#59]
Add basic CI with GithubAction to at least compile and test the project.

**Comment by mkurz** [comment]
Actually we are in the progress of moving from Travis CI to GitHub actions. So what we did is we have some central reusable workflows which might help you here as well: https://github.com/playframework/.github/tree/main/.github/workflows
For example have a look how we use that reusable workflows here:
* https://github.com/playframework/play-json/blob/main/.github/workflows/build-test.yml
* https://github.com/playframework/play-ws/tree/main/.github/workflows
* https://github.com/playframework/play-soap/blob/main/.github/workflows/build-test.yml
