### ISSUE TITLE
Setup Scala Steward

### ISSUE THREAD

**Issue by ptrdom** [playframework/play-scala-react-seed#61]
Add Scala Steward setup so that dependency update can be automated. 
https://github.com/scala-steward-org/scala-steward-action

**Comment by mkurz** [comment]
@ptrdom You don't need to set up the scala-steward GitHub actions. All that needs to be done is add the repos to the official scala-steward list and then scala steward will come and visit this repo and update them. Just have a look at https://github.com/scala-steward-org/repos/pull/939 where I added other repos to that list.

**Comment by ptrdom** [comment]
Oh, that is awesome! Never set it up before, a quick glance did not point to the fact that it is so simple 😄

**Comment by ptrdom** [comment]
https://github.com/scala-steward-org/repos/pull/1002

**Comment by ptrdom** [comment]
Done.
